chore: fix bluetooth

diff --git a/scripts/bin/pwnlib b/scripts/bin/pwnlib
--- a/scripts/bin/pwnlib
+++ b/scripts/bin/pwnlib
@@ -12,13 +12,14 @@ fi
 
 # Starts monitor interface
 start_monitor_interface() {
+	rfkill unblock all
 	if ! exists_dev_interface "${PWNAGOTCHI_IFACE_MON:?}"; then
 		if exists_phy_interface "${PWNAGOTCHI_IFACE_NET:?}"; then
 			iw phy "${PWNAGOTCHI_IFACE_NET:?}" interface add "${PWNAGOTCHI_IFACE_MON:?}" type monitor
 		elif exists_dev_interface "${PWNAGOTCHI_IFACE_NET:?}"; then
 			iw dev "${PWNAGOTCHI_IFACE_NET:?}" interface add "${PWNAGOTCHI_IFACE_MON:?}" type monitor
 		else
-			>&2 printf '%s\n' "'${PWNAGOTCHI_IFACE_NET:?}' interface could not be found"
+			printf >&2 '%s\n' "'${PWNAGOTCHI_IFACE_NET:?}' interface could not be found"
 			exit 1
 		fi
 	fi
