chore: refactor pwnlib a little

diff --git a/scripts/bin/pwnlib b/scripts/bin/pwnlib
--- a/scripts/bin/pwnlib
+++ b/scripts/bin/pwnlib
@@ -23,7 +23,8 @@ start_monitor_interface() {
 	fi
 
 	# MONITOR
-	if ! exists_dev_interface "${PWNAGOTCHI_IFACE_MON:?}" && [ "${PWNAGOTCHI_IFACE_MON}" != "${PWNAGOTCHI_IFACE_NET}" ]; then
+	if ! exists_dev_interface "${PWNAGOTCHI_IFACE_MON:?}" &&
+		[ "${PWNAGOTCHI_IFACE_MON}" != "${PWNAGOTCHI_IFACE_NET}" ]; then
 		if exists_phy_interface "${PWNAGOTCHI_IFACE_NET:?}"; then
 			iw phy "${PWNAGOTCHI_IFACE_NET:?}" interface add "${PWNAGOTCHI_IFACE_MON:?}" type monitor
 		elif exists_dev_interface "${PWNAGOTCHI_IFACE_NET:?}"; then
@@ -43,23 +44,29 @@ start_monitor_interface() {
 	fi
 
 	# PWNGRID
-	if ! exists_dev_interface "${PWNAGOTCHI_PWNGRID_MON:?}" && [ "${PWNAGOTCHI_PWNGRID_MON}" != "${PWNAGOTCHI_PWNGRID_NET}" ]; then
-		if exists_phy_interface "${PWNAGOTCHI_PWNGRID_NET:?}"; then
-			iw phy "${PWNAGOTCHI_PWNGRID_NET:?}" interface add "${PWNAGOTCHI_PWNGRID_MON:?}" type monitor
-		elif exists_dev_interface "${PWNAGOTCHI_PWNGRID_NET:?}"; then
-			iw dev "${PWNAGOTCHI_PWNGRID_NET:?}" interface add "${PWNAGOTCHI_PWNGRID_MON:?}" type monitor
-		else
-			printf >&2 '%s\n' "'${PWNAGOTCHI_PWNGRID_NET:?}' interface could not be found"
-			exit 1
+	# Pwngrid need a "mon" interface, but I can't make working
+	# the AWUS036ACS with the 8821au driver with a dedicated mon0 monitoring interface,
+	# thus I will use the builtin wifi card to pwngrid when needed.
+	if [ "${PWNAGOTCHI_PWNGRID_MON}" != "${PWNAGOTCHI_PWNGRID_NET}" ] &&
+		[ "${PWNAGOTCHI_PWNGRID_MON}" != "${PWNAGOTCHI_IFACE_MON}" ]; then
+		if ! exists_dev_interface "${PWNAGOTCHI_PWNGRID_MON:?}"; then
+			if exists_phy_interface "${PWNAGOTCHI_PWNGRID_NET:?}"; then
+				iw phy "${PWNAGOTCHI_PWNGRID_NET:?}" interface add "${PWNAGOTCHI_PWNGRID_MON:?}" type monitor
+			elif exists_dev_interface "${PWNAGOTCHI_PWNGRID_NET:?}"; then
+				iw dev "${PWNAGOTCHI_PWNGRID_NET:?}" interface add "${PWNAGOTCHI_PWNGRID_MON:?}" type monitor
+			else
+				printf >&2 '%s\n' "'${PWNAGOTCHI_PWNGRID_NET:?}' interface could not be found"
+				exit 1
+			fi
 		fi
-	fi
 
-	if [ "${PWNAGOTCHI_PWNGRID_MON}" = "${PWNAGOTCHI_PWNGRID_NET}" ]; then
-		iw "${PWNAGOTCHI_PWNGRID_NET}" set monitor control
-	fi
+		if [ "${PWNAGOTCHI_PWNGRID_MON}" = "${PWNAGOTCHI_PWNGRID_NET}" ]; then
+			iw "${PWNAGOTCHI_PWNGRID_NET}" set monitor control
+		fi
 
-	if ! is_dev_interface_up "${PWNAGOTCHI_PWNGRID_NET:?}"; then
-		ip link set "${PWNAGOTCHI_PWNGRID_MON:?}" up
+		if ! is_dev_interface_up "${PWNAGOTCHI_PWNGRID_NET:?}"; then
+			ip link set "${PWNAGOTCHI_PWNGRID_MON:?}" up
+		fi
 	fi
 }
 
